import { h, p, statement, grid, testimonial, table, images, PRICING, ACCEPT, ART } from "./templateKit";
import type { Template } from "./templateKit";

// Trade templates: one per profession, each a full proposal with realistic prices. They are reached from the
// public template pages (and by ?template=id), not from the in-app picker, which stays at seven.

const terms = (text: string) => [h(2, "Terms"), p(text), ACCEPT];
const pricing = (lead = "Choose the options you want below. The total updates as you go.") => [h(2, "Pricing", "gray"), p(lead), PRICING];

export const TRADE_TEMPLATES: Template[] = [
  {
    id: "logo-design",
    group: "trade",
    trade: "Design",
    style: "studio",
    name: "Logo design",
    summary: "Three directions, one refined mark, and the files a business needs for the next ten years.",
    title: "A new logo for Harbor Coffee",
    content: [
      statement("A mark that works on a cup, a sign and a phone screen. Three directions, one finished logo, every file you will ever need."),
      p("You have outgrown the logo you started with. This proposal sets out how we get to a mark you are proud of, in three weeks, without endless rounds."),
      images([{ url: ART.warm, caption: "Direction one: warm, handmade" }, { url: ART.cool, caption: "Direction two: clean, modern" }]),
      h(2, "What you get", "orange"),
      grid([
        { title: "Three directions", text: "Three distinct logo concepts presented in context: on a cup, a storefront and a social profile." },
        { title: "One refined mark", text: "Your chosen direction taken to a finished logo, with a horizontal and a stacked version." },
        { title: "Every file", text: "Vector, PNG and SVG, in colour, black and white, with a one-page guide to using them." },
      ]),
      h(2, "How it works"),
      table([
        ["Week", "What happens", "You get"],
        ["1", "Discovery call, then three directions", "A presentation to react to"],
        ["2", "Refine the chosen direction", "The near-final logo, two rounds of changes"],
        ["3", "Final files and the guide", "A folder that works everywhere"],
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("We put the new mark on the window the day the files arrived. People noticed within the week.", "Maya Lindqvist", "Owner, Harbor Coffee"),
      ...pricing(),
      ...terms("Half is invoiced when you accept and half at delivery. Two rounds of changes are included in the refinement week; further rounds are quoted. You own the final logo outright once the final invoice is paid."),
    ],
    items: [
      { name: "Logo design", description: "Three directions, one refined mark, all files", unitAmount: 180000, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null },
      { name: "Brand colours and type", description: "A palette and two typefaces chosen to go with the mark", unitAmount: 45000, quantity: 1, optional: true, selectedByDefault: true, taxRateBps: null },
      { name: "Business cards", description: "Print-ready card design, front and back", unitAmount: 25000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null },
      { name: "Extra directions", description: "Beyond the three included", unitAmount: 40000, quantity: 0, minQuantity: 0, maxQuantity: 3, optional: true, selectedByDefault: false, taxRateBps: null, unit: "direction" },
    ],
  },
  {
    id: "seo-retainer",
    group: "trade",
    trade: "Marketing",
    style: "bold",
    name: "SEO retainer",
    summary: "Six months of search work with a monthly report the client can actually read.",
    title: "SEO for the next six months",
    content: [
      statement("More of the right people finding you on Google, measured every month, with nothing hidden in jargon."),
      p("Your site ranks for your name and not much else. This is a six-month plan to change that, with a fixed monthly fee and a report that shows what moved."),
      h(2, "What you get", "green"),
      grid([
        { title: "Technical fixes first", text: "Speed, structure and the errors search engines trip on, fixed in month one." },
        { title: "Pages that answer searches", text: "Two new pages a month written around what your customers actually type." },
        { title: "Links from real sites", text: "Outreach to directories, suppliers and local press that count." },
      ]),
      h(2, "How it works"),
      table([
        ["Month", "Focus", "You get"],
        ["1", "Audit and technical fixes", "A plain-English audit and a fixed site"],
        ["2 to 5", "Content and links, two pages a month", "A one-page report on the first of each month"],
        ["6", "Review and the plan for the next six", "A meeting and a written recommendation"],
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("Month four was the first time a stranger found us on Google and called. It has not stopped since.", "Owen Ferris", "Ferris Plumbing"),
      ...pricing("The monthly fee below runs for six months. Add the options you want."),
      ...terms("Billed monthly in advance. Either side can end the retainer with thirty days' notice after month three. Rankings depend on many things; we commit to the work in this proposal, not to a position."),
    ],
    items: [
      { name: "SEO retainer", description: "Technical work, two pages a month, links and a monthly report", unitAmount: 150000, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null, billing: "month" },
      { name: "Google Business Profile", description: "Set up or clean up, with weekly posts", unitAmount: 25000, quantity: 1, optional: true, selectedByDefault: true, taxRateBps: null, billing: "month" },
      { name: "Extra pages", description: "Beyond the two a month", unitAmount: 35000, quantity: 0, minQuantity: 0, maxQuantity: 6, optional: true, selectedByDefault: false, taxRateBps: null, unit: "page", billing: "month" },
    ],
  },
  {
    id: "social-media",
    group: "trade",
    trade: "Marketing",
    style: "warm",
    name: "Social media management",
    summary: "A month of posts, planned and published, with the numbers each month.",
    title: "Social media, done every week",
    content: [
      statement("Your accounts posted to every week by someone who knows your business, with a calendar you approve in advance."),
      p("You know you should post and you never have the time. This proposal covers planning, writing, designing and publishing, so your accounts stay alive while you run the business."),
      images([{ url: ART.warm, caption: "A month of posts, laid out" }, { url: ART.sage, caption: "Story and reel formats" }]),
      h(2, "What you get", "pink"),
      grid([
        { title: "A monthly calendar", text: "Every post planned and sent to you for approval a week before it goes out." },
        { title: "Written and designed", text: "Captions in your voice and graphics in your brand, three posts a week." },
        { title: "The numbers", text: "A short report each month: followers, reach, and which posts did the work." },
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("I stopped feeling guilty about Instagram. It just happens now, and it looks like us.", "Priya Desai", "Desai Bakery"),
      ...pricing("The monthly fee below runs month to month. Add what you need."),
      ...terms("Billed monthly in advance. Cancel with fourteen days' notice. You approve every calendar before anything is published, and you own the content we make."),
    ],
    items: [
      { name: "Social media management", description: "Three posts a week on two platforms, calendar, publishing, report", unitAmount: 90000, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null, billing: "month" },
      { name: "Reels and short video", description: "Filmed on site, edited and captioned", unitAmount: 15000, quantity: 0, minQuantity: 0, maxQuantity: 8, optional: true, selectedByDefault: false, taxRateBps: null, unit: "video", billing: "month" },
      { name: "Community replies", description: "Comments and messages answered within a working day", unitAmount: 30000, quantity: 1, optional: true, selectedByDefault: true, taxRateBps: null, billing: "month" },
    ],
  },
  {
    id: "copywriting",
    group: "trade",
    trade: "Marketing",
    style: "editorial",
    name: "Website copywriting",
    summary: "Every page of the site written, with a clear voice and a call to action that fits.",
    title: "Words for the new site",
    content: [
      statement("Five pages that say what you do, who it is for and why you, in the voice your customers already hear on the phone."),
      p("A new site with the old words is the old site. This proposal covers interviews, a voice guide, and every page written and edited, ready for the designer."),
      h(2, "What you get", "purple"),
      grid([
        { title: "Two interviews", text: "An hour with you and an hour with a customer, so the words come from real conversations." },
        { title: "A short voice guide", text: "One page on how you sound, so everything written after this matches." },
        { title: "Five pages, edited", text: "Home, services, about, work, contact, each with a headline, body and call to action." },
      ]),
      h(2, "How it works"),
      table([
        ["Week", "What happens", "You get"],
        ["1", "Interviews and the voice guide", "A one-page guide to approve"],
        ["2", "First drafts of every page", "A document with comments open"],
        ["3", "Your changes, then the final edit", "Clean copy, handed to your designer"],
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("She wrote it the way I would say it if I were good at saying it.", "Tom Achebe", "Achebe Electrical"),
      ...pricing(),
      ...terms("Half on acceptance, half at delivery. Two rounds of changes are included. Extra pages are quoted at the per-page rate below."),
    ],
    items: [
      { name: "Website copy, five pages", description: "Interviews, voice guide, five pages written and edited", unitAmount: 240000, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null },
      { name: "Extra pages", description: "Beyond the five included", unitAmount: 35000, quantity: 0, minQuantity: 0, maxQuantity: 10, optional: true, selectedByDefault: false, taxRateBps: null, unit: "page" },
      { name: "Email welcome series", description: "Three emails for new subscribers", unitAmount: 60000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null },
    ],
  },
  {
    id: "video-production",
    group: "trade",
    trade: "Photography and video",
    style: "night",
    name: "Video production",
    summary: "A ninety-second brand film, from script to final cut, with the short cuts for social.",
    title: "A brand film in ninety seconds",
    content: [
      statement("One film that shows what it is like to work with you, shot in a day, cut for your site and your social accounts."),
      p("People decide in seconds whether they trust a business. A short film of your team at work does more than a page of text. Here is how we make it."),
      images([{ url: ART.deep, caption: "Frame from the opening" }, { url: ART.cool, caption: "Interview setup" }]),
      h(2, "What you get", "blue"),
      grid([
        { title: "Script and plan", text: "A short script and a shot list agreed before the shoot day, so nothing is left to chance." },
        { title: "One shoot day", text: "Two cameras, sound, lighting and a director on site for up to eight hours." },
        { title: "The film and the cuts", text: "A ninety-second film, three fifteen-second cuts for social, and captions." },
      ]),
      h(2, "How it works"),
      table([
        ["Step", "What happens", "You get"],
        ["Pre-production", "Interview questions, script, shot list", "A plan to approve"],
        ["Shoot day", "On site, two cameras", "Everything captured in one day"],
        ["Edit", "First cut in ten working days, two rounds of changes", "Final films in every format you need"],
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("The film on our homepage does the first half of every sales call for us now.", "Lena Bosch", "Bosch Joinery"),
      ...pricing(),
      ...terms("Half on acceptance, half on delivery of the final cut. Two rounds of changes are included. Music is licensed for web and social use. Raw footage is kept for one year."),
    ],
    items: [
      { name: "Brand film", description: "Script, one shoot day, ninety-second film with two rounds of changes", unitAmount: 480000, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null },
      { name: "Social cuts", description: "Three fifteen-second vertical cuts with captions", unitAmount: 60000, quantity: 1, optional: true, selectedByDefault: true, taxRateBps: null },
      { name: "Extra shoot days", description: "A second location or a second day", unitAmount: 180000, quantity: 0, minQuantity: 0, maxQuantity: 3, optional: true, selectedByDefault: false, taxRateBps: null, unit: "day" },
      { name: "Drone footage", description: "Exterior and site shots, where permitted", unitAmount: 55000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null },
    ],
  },
  {
    id: "wedding-photography",
    group: "trade",
    trade: "Photography and video",
    style: "warm",
    name: "Wedding photography",
    summary: "A full day, two photographers if you want them, and a gallery within six weeks.",
    title: "Your wedding, photographed",
    content: [
      statement("From getting ready to the last dance, photographed the way it felt, delivered in a gallery you can share with everyone."),
      p("Thank you for asking. Here is exactly what the day includes, what it costs, and what you can add. Nothing is decided until you say so."),
      images([{ url: ART.warm, caption: "Golden hour portraits" }, { url: ART.sage, caption: "Candid, unposed" }]),
      h(2, "What you get", "pink"),
      grid([
        { title: "Ten hours of coverage", text: "From the morning preparations to the first hour of the party, one lead photographer." },
        { title: "A private online gallery", text: "Around six hundred edited photos within six weeks, downloadable in full resolution." },
        { title: "A planning call", text: "A month before, we go through the timeline and the people who matter most." },
      ]),
      h(2, "What couples say", "yellow"),
      testimonial("We did not notice her all day, and then the photos arrived and she had seen everything.", "Hannah and Luis", "Married in June"),
      ...pricing("Choose the day you want below. The total updates as you go."),
      ...terms("A 25% booking fee holds the date and is not refundable. The balance is due two weeks before the wedding. Galleries are kept online for one year. Travel within 50 km is included; beyond that is quoted."),
    ],
    items: [
      { name: "Full day coverage", description: "Ten hours, one photographer, edited gallery", unitAmount: 320000, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null },
      { name: "Second photographer", description: "Both sides of the morning and more of the guests", unitAmount: 80000, quantity: 1, optional: true, selectedByDefault: true, taxRateBps: null },
      { name: "Engagement session", description: "An hour, a location of your choice, forty photos", unitAmount: 45000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null },
      { name: "Extra hours", description: "Beyond the ten included", unitAmount: 30000, quantity: 0, minQuantity: 0, maxQuantity: 4, optional: true, selectedByDefault: false, taxRateBps: null, unit: "hour" },
      { name: "Printed album", description: "Thirty pages, linen cover, designed by us", unitAmount: 65000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null },
    ],
  },
  {
    id: "bookkeeping",
    group: "trade",
    trade: "Business services",
    style: "classic",
    name: "Bookkeeping",
    summary: "Monthly books, reconciled and reported, with year-end ready to hand over.",
    title: "Monthly bookkeeping",
    content: [
      statement("Your books done every month, reconciled to the bank, with a short report so you always know where you stand."),
      p("You are behind on the books and it costs you at tax time. This proposal covers catching up, then a fixed monthly service so it never happens again."),
      h(2, "What you get", "green"),
      grid([
        { title: "Every transaction recorded", text: "Bank and card feeds categorised weekly, receipts matched, questions asked once a month." },
        { title: "Reconciled and reported", text: "Bank accounts reconciled monthly, with a profit and loss and a balance sheet you can read." },
        { title: "Year-end ready", text: "A clean file handed to your accountant, or to us, when the year closes." },
      ]),
      h(2, "How it works"),
      table([
        ["When", "What happens", "You get"],
        ["Month 1", "Catch-up of the current year", "Books current to date"],
        ["Monthly", "Categorise, reconcile, report by the 10th", "A two-page report"],
        ["Quarterly", "Sales tax filed", "Confirmation and the amount due"],
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("First year I have not dreaded April. Everything was already done.", "Grace Okafor", "Okafor Dental"),
      ...pricing("The monthly fee below runs month to month. Add the catch-up if you are behind."),
      ...terms("Billed monthly in advance. The catch-up is billed once. You keep full access to your accounting software; we work inside it. Cancel with thirty days' notice."),
    ],
    items: [
      { name: "Monthly bookkeeping", description: "Up to 150 transactions a month, reconciled and reported", unitAmount: 45000, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null, billing: "month" },
      { name: "Catch-up", description: "Bring the current year up to date, per month behind", unitAmount: 30000, quantity: 3, minQuantity: 0, maxQuantity: 12, optional: true, selectedByDefault: true, taxRateBps: null, unit: "month" },
      { name: "Sales tax filing", description: "Quarterly returns prepared and filed", unitAmount: 12000, quantity: 1, optional: true, selectedByDefault: true, taxRateBps: null, billing: "month" },
      { name: "Payroll", description: "Up to five employees, twice a month", unitAmount: 20000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null, billing: "month" },
    ],
  },
  {
    id: "business-coaching",
    group: "trade",
    trade: "Business services",
    style: "editorial",
    name: "Business coaching",
    summary: "Twelve weeks, one call a week, and a plan you actually follow between calls.",
    title: "Twelve weeks of coaching",
    content: [
      statement("Twelve weeks to get the business working for you rather than the other way round, with someone in your corner every week."),
      p("You told me the business runs on you and stalls when you stop. Over twelve weeks we change that, one decision at a time, with homework that fits a real week."),
      h(2, "What you get", "purple"),
      grid([
        { title: "A weekly call", text: "Sixty minutes, same time each week, with notes and actions sent within the hour." },
        { title: "A ninety-day plan", text: "Written in week one and revisited every fourth week, so we can see what moved." },
        { title: "Between calls", text: "Messages answered within a working day when something comes up." },
      ]),
      h(2, "How it works"),
      table([
        ["Weeks", "Focus", "You get"],
        ["1 to 2", "Where the time and money go", "A clear picture and the plan"],
        ["3 to 10", "One change a week, held to", "Momentum you can measure"],
        ["11 to 12", "What to keep and what to stop", "The next ninety days, written down"],
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("I took my first two-week holiday in six years during week nine. The business was fine.", "Daniel Roux", "Roux Roofing"),
      ...pricing("Choose how you would like to work together below."),
      ...terms("The twelve-week programme is billed in three monthly instalments. Missed calls can be moved once with a day's notice. Everything discussed stays between us."),
    ],
    items: [
      { name: "Twelve-week coaching programme", description: "Twelve weekly calls, the plan, messages between calls", unitAmount: 360000, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null },
      { name: "Team session", description: "A half-day workshop with your team on the plan", unitAmount: 120000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null },
      { name: "Monthly follow-up", description: "One call a month after the programme ends", unitAmount: 35000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null, billing: "month" },
    ],
  },
  {
    id: "interior-design",
    group: "trade",
    trade: "Design",
    style: "studio",
    name: "Interior design",
    summary: "Concept, drawings and a shopping list for two rooms, with sourcing if you want it.",
    title: "Living room and kitchen redesign",
    content: [
      statement("Two rooms that finally feel like one home: a concept you can picture, drawings your builder can use, and a list of everything to buy."),
      p("You have a house you love and two rooms that do not work. This proposal takes them from ideas to a plan with prices, and can carry on through the build if you want a second pair of eyes."),
      images([{ url: ART.sage, caption: "Concept: living room" }, { url: ART.warm, caption: "Concept: kitchen" }]),
      h(2, "What you get", "green"),
      grid([
        { title: "A concept for each room", text: "Mood, layout and materials presented as boards you can react to, two options per room." },
        { title: "Drawings", text: "Floor plans and elevations at a scale a builder or joiner can price from." },
        { title: "A sourcing list", text: "Every fitting, finish and piece of furniture with a supplier and a price." },
      ]),
      h(2, "How it works"),
      table([
        ["Step", "What happens", "You get"],
        ["Survey", "Measure both rooms, talk through how you live", "A brief we both sign off"],
        ["Concept", "Two options per room, presented at your home", "Boards to choose from"],
        ["Drawings and list", "The chosen option drawn up", "Plans, elevations, the shopping list"],
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("The builder said it was the first time a client had turned up with drawings he could actually use.", "Sara and Ben", "Homeowners"),
      ...pricing(),
      ...terms("The design fee is billed half on acceptance and half at delivery of the drawings. Site visits during the build are billed monthly. Furniture and fittings are bought by you directly at the prices on the list."),
    ],
    items: [
      { name: "Design package, two rooms", description: "Survey, concepts, drawings and the sourcing list", unitAmount: 380000, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null },
      { name: "Site visits during the build", description: "Half a day each, to check the work against the drawings", unitAmount: 45000, quantity: 0, minQuantity: 0, maxQuantity: 8, optional: true, selectedByDefault: false, taxRateBps: null, unit: "visit" },
      { name: "Sourcing and ordering", description: "We place and track every order for you", unitAmount: 90000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null },
    ],
  },
  {
    id: "landscaping",
    group: "trade",
    trade: "Home and trades",
    style: "warm",
    name: "Landscaping",
    summary: "A front garden and patio, designed and built, with planting the client can scale.",
    title: "Front garden and patio",
    content: [
      statement("A front garden you are glad to come home to and a patio you use every evening in summer, built in three weeks."),
      p("You asked for less lawn, more room to sit, and something that looks good in winter too. Here is the plan, the timeline and the price, with the planting sized to your budget."),
      images([{ url: ART.sage, caption: "Planting plan" }, { url: ART.warm, caption: "Patio in the evening" }]),
      h(2, "What you get", "green"),
      grid([
        { title: "A plan to scale", text: "A drawn plan of the whole space, with the patio, paths, beds and lighting marked." },
        { title: "The build", text: "Groundwork, a porcelain patio of twenty square metres, edging and paths, by our own team." },
        { title: "Planting that lasts", text: "Plants chosen for your soil and light, planted by us, with a care sheet for the first year." },
      ]),
      h(2, "How it works"),
      table([
        ["Week", "What happens", "You get"],
        ["1", "Clearance and groundwork", "The space ready for building"],
        ["2", "Patio, edging and lighting", "The hard landscaping finished"],
        ["3", "Planting and the tidy-up", "A garden, and the care sheet"],
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("Neighbours we had never spoken to stopped to ask who did it.", "Fiona Marsh", "Homeowner"),
      ...pricing("Choose the planting and extras you want below. The total updates as you go."),
      ...terms("A 30% deposit secures the start date and the materials. The balance is due on completion. Weather can move the schedule by a few days; we will tell you the day before. Plants carry a one-year replacement guarantee when the care sheet is followed."),
    ],
    items: [
      { name: "Design and build", description: "Plan, groundwork, 20 square metre patio, paths and edging", unitAmount: 1250000, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null },
      { name: "Planting", description: "Plants, soil improvement and planting, per bed", unitAmount: 65000, quantity: 3, minQuantity: 1, maxQuantity: 8, optional: true, selectedByDefault: true, taxRateBps: null, unit: "bed" },
      { name: "Garden lighting", description: "Six low-voltage lights on a timer", unitAmount: 140000, quantity: 1, optional: true, selectedByDefault: true, taxRateBps: null },
      { name: "Seasonal maintenance", description: "Four visits a year", unitAmount: 18000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null, billing: "quarter" },
    ],
  },
  {
    id: "cleaning-services",
    group: "trade",
    trade: "Home and trades",
    style: "classic",
    name: "Cleaning services",
    summary: "A weekly office clean with a fixed monthly price and extras the client can add.",
    title: "Weekly cleaning for your office",
    content: [
      statement("A clean office every Monday morning, the same two people every week, at a price that does not change."),
      p("You asked for a reliable clean that does not need chasing. This proposal sets out what we do on each visit, who does it, and what it costs each month."),
      h(2, "What you get", "green"),
      grid([
        { title: "Every visit", text: "Desks, floors, kitchen, bathrooms, bins and glass, on a checklist we leave on the counter." },
        { title: "The same team", text: "Two trained, insured cleaners you will get to know, with a supervisor visit once a month." },
        { title: "Supplies included", text: "All products and equipment, with eco-certified options at no extra cost." },
      ]),
      h(2, "How it works"),
      table([
        ["When", "What happens", "You get"],
        ["Before we start", "A walk-through and a written checklist", "A plan you approve"],
        ["Weekly", "Two-hour visit, outside your hours", "A signed checklist each time"],
        ["Monthly", "Supervisor check and a quick call", "Anything missed, fixed"],
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("Two years, never a missed Monday. That is all I wanted.", "Karen Whitfield", "Office manager, Whitfield Legal"),
      ...pricing("Choose the visits and extras you want below."),
      ...terms("Billed monthly in advance. Either side can end the agreement with thirty days' notice. We are insured for public liability and treat your keys and alarm codes as confidential."),
    ],
    items: [
      { name: "Weekly office clean", description: "One two-hour visit a week, two cleaners, supplies included", unitAmount: 64000, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null, billing: "month" },
      { name: "Extra weekly visits", description: "Additional visits per week", unitAmount: 60000, quantity: 0, minQuantity: 0, maxQuantity: 4, optional: true, selectedByDefault: false, taxRateBps: null, unit: "visit a week", billing: "month" },
      { name: "Carpet deep clean", description: "Twice a year, all carpeted areas", unitAmount: 38000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null, billing: "quarter" },
      { name: "Window cleaning", description: "Inside and out, monthly", unitAmount: 12000, quantity: 1, optional: true, selectedByDefault: true, taxRateBps: null, billing: "month" },
    ],
  },
  {
    id: "home-renovation",
    group: "trade",
    trade: "Home and trades",
    style: "bold",
    name: "Home renovation",
    summary: "A kitchen renovation with a fixed scope, a schedule, and upgrades the client can choose.",
    title: "Kitchen renovation",
    content: [
      statement("A new kitchen in five weeks, with one contractor responsible for everything and a price that only changes if you change it."),
      p("You want a kitchen that works, done by people who turn up. This proposal fixes the scope and the schedule, and lists the upgrades so you can decide with the numbers in front of you."),
      images([{ url: ART.warm, caption: "Layout" }, { url: ART.sage, caption: "Finishes" }]),
      h(2, "What you get", "orange"),
      grid([
        { title: "One point of contact", text: "We run the joiner, the electrician, the plumber and the tiler. You talk to one person." },
        { title: "A fixed scope", text: "Strip-out, first fix, units, worktop, tiling, second fix, decoration and a clean handover." },
        { title: "A written schedule", text: "Five weeks, day by day, with the days you will be without water or power marked." },
      ]),
      h(2, "How it works"),
      table([
        ["Week", "What happens", "Live with"],
        ["1", "Strip-out, first fix electrics and plumbing", "No kitchen; a temporary sink"],
        ["2 to 3", "Units, worktop template and fit", "Units in, no worktop for four days"],
        ["4 to 5", "Tiling, second fix, decoration, handover", "Your kitchen, with a snag list closed"],
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("Finished on the Friday they said, and the site was cleaner at the end than when they arrived.", "Amira Haddad", "Homeowner"),
      ...pricing("Choose the upgrades you want below. The total updates as you go."),
      ...terms("A 20% deposit on acceptance, 40% at the end of week two, the balance on handover. Changes you ask for after the schedule is agreed are quoted before they are done. Work is guaranteed for two years."),
    ],
    items: [
      { name: "Kitchen renovation", description: "Strip-out to handover, labour and standard materials", unitAmount: 2400000, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null },
      { name: "Stone worktop upgrade", description: "Quartz in place of laminate", unitAmount: 320000, quantity: 1, optional: true, selectedByDefault: true, taxRateBps: null },
      { name: "Underfloor heating", description: "Electric mat under the tiled floor", unitAmount: 140000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null },
      { name: "Extra sockets", description: "Beyond the eight included", unitAmount: 9000, quantity: 0, minQuantity: 0, maxQuantity: 10, optional: true, selectedByDefault: false, taxRateBps: null, unit: "socket" },
    ],
  },
  {
    id: "event-planning",
    group: "trade",
    trade: "Events and personal",
    style: "warm",
    name: "Event planning",
    summary: "A company event for eighty people, planned and run, with the extras the client picks.",
    title: "Your summer event, planned and run",
    content: [
      statement("An evening for eighty people that your team talks about afterwards, and that you do not have to run yourself."),
      p("You told me the last event took three weeks of your time and still felt thrown together. This is what it looks like when someone else carries it, from venue to the last taxi."),
      h(2, "What you get", "pink"),
      grid([
        { title: "Venue and suppliers", text: "Three venue options within budget, then catering, drinks, sound and decoration booked and managed." },
        { title: "A run sheet", text: "The evening planned to the quarter hour, shared with every supplier a week before." },
        { title: "On the night", text: "A planner and an assistant on site from setup to close, so nobody from your team is working." },
      ]),
      h(2, "How it works"),
      table([
        ["When", "What happens", "You get"],
        ["Eight weeks out", "Brief, budget, venue shortlist", "A venue booked"],
        ["Four weeks out", "Suppliers confirmed, invitations sent", "A run sheet and a guest list"],
        ["The day", "Setup, the event, breakdown", "An evening you attend as a guest"],
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("I sat down with a drink at seven and did not stand up to fix anything all night.", "James Okoro", "Founder, Okoro Studio"),
      ...pricing("Choose the extras you want below."),
      ...terms("The planning fee is billed half on acceptance and half a week before the event. Venue and supplier costs are paid by you directly on their invoices, which we check first. Cancellation more than four weeks out forfeits the first half only."),
    ],
    items: [
      { name: "Planning and running the event", description: "Venue, suppliers, run sheet and two people on the night", unitAmount: 420000, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null },
      { name: "Photographer", description: "Four hours on the night, edited gallery within a week", unitAmount: 90000, quantity: 1, optional: true, selectedByDefault: true, taxRateBps: null },
      { name: "Live music", description: "A three-piece band for two sets", unitAmount: 160000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null },
      { name: "Extra guests", description: "Planning and on-the-night cover beyond eighty, per ten", unitAmount: 25000, quantity: 0, minQuantity: 0, maxQuantity: 6, optional: true, selectedByDefault: false, taxRateBps: null, unit: "ten guests" },
    ],
  },
  {
    id: "catering",
    group: "trade",
    trade: "Events and personal",
    style: "warm",
    name: "Catering",
    summary: "A plated dinner for sixty, with the courses and drinks the client chooses.",
    title: "Dinner for sixty",
    content: [
      statement("A three-course dinner cooked on site for sixty guests, served by our team, with the menu shaped around what you love."),
      p("Thank you for asking us to cook for your evening. Here is the menu we discussed, how the service runs, and the price, with the choices left open for you."),
      images([{ url: ART.warm, caption: "The main course" }, { url: ART.sage, caption: "Table setting" }]),
      h(2, "What you get", "orange"),
      grid([
        { title: "A seasonal menu", text: "A tasting a month before, then a menu fixed for the night, with dietary needs handled quietly." },
        { title: "Cooked on site", text: "Our kitchen team arrives four hours before service; nothing is reheated from a van." },
        { title: "Served and cleared", text: "One server per ten guests, table service, and the kitchen left as we found it." },
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("Guests asked for the recipe for the dessert. They still ask.", "Elena Petrova", "Host"),
      ...pricing("Choose the courses and extras you want below. Prices are per guest where marked."),
      ...terms("A 30% deposit holds the date. Final numbers are due ten days before; the balance is invoiced after the event. Menu changes within seven days of the event are subject to availability."),
    ],
    items: [
      { name: "Three-course dinner", description: "Per guest, cooked on site and served", unitAmount: 9500, quantity: 60, minQuantity: 30, maxQuantity: 120, optional: false, selectedByDefault: true, taxRateBps: null, unit: "guest" },
      { name: "Canapés on arrival", description: "Per guest, four pieces", unitAmount: 1800, quantity: 60, minQuantity: 0, maxQuantity: 120, optional: true, selectedByDefault: true, taxRateBps: null, unit: "guest" },
      { name: "Wine pairing", description: "Per guest, a glass with each course", unitAmount: 2600, quantity: 60, minQuantity: 0, maxQuantity: 120, optional: true, selectedByDefault: false, taxRateBps: null, unit: "guest" },
      { name: "Tableware and linen hire", description: "Plates, glassware, cutlery, linen, delivered and collected", unitAmount: 48000, quantity: 1, optional: true, selectedByDefault: true, taxRateBps: null },
    ],
  },
  {
    id: "personal-training",
    group: "trade",
    trade: "Events and personal",
    style: "bold",
    name: "Personal training",
    summary: "A twelve-week block with sessions the client sets the number of, plus nutrition.",
    title: "Twelve weeks, stronger",
    content: [
      statement("Twelve weeks of training built around your schedule and your knees, with a plan for the days we are not in the gym."),
      p("You want to get strong without getting hurt, and you want it to fit around work. Here is how the twelve weeks run, what each week includes, and the price for the number of sessions you choose."),
      h(2, "What you get", "green"),
      grid([
        { title: "Sessions with me", text: "Fifty-five minutes, programmed in advance, with every lift tracked so you can see the numbers move." },
        { title: "A plan for the other days", text: "Two short home sessions a week in the app, with videos, so twelve weeks means twelve weeks." },
        { title: "A check-in every Sunday", text: "Ten minutes on the phone: what worked, what hurt, what changes." },
      ]),
      h(2, "How it works"),
      table([
        ["Weeks", "Focus", "You get"],
        ["1 to 4", "Technique and the base", "Confidence with every lift"],
        ["5 to 8", "Load goes up", "Visible strength and the habit"],
        ["9 to 12", "Push, then test", "Numbers to compare with week one"],
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("Week one I could not do a push-up. Week twelve I did fifteen.", "Nadia Hussain", "Client"),
      ...pricing("Choose how many sessions a week you want below. The total updates as you go."),
      ...terms("The block is billed in three monthly instalments. Sessions cancelled with less than twelve hours' notice are counted as used. The block can be paused once for up to two weeks."),
    ],
    items: [
      { name: "Training sessions", description: "Fifty-five minutes each, over twelve weeks", unitAmount: 7500, quantity: 24, minQuantity: 12, maxQuantity: 48, optional: false, selectedByDefault: true, taxRateBps: null, unit: "session" },
      { name: "Nutrition plan", description: "A plan built around what you already eat, reviewed monthly", unitAmount: 18000, quantity: 1, optional: true, selectedByDefault: true, taxRateBps: null },
      { name: "Partner sessions", description: "Bring someone; the session price covers both", unitAmount: 3500, quantity: 0, minQuantity: 0, maxQuantity: 24, optional: true, selectedByDefault: false, taxRateBps: null, unit: "session" },
    ],
  },
  {
    id: "marketing-retainer",
    group: "trade",
    trade: "Marketing",
    style: "studio",
    name: "Marketing retainer",
    summary: "A fractional marketing team by the month, with channels the client switches on.",
    title: "Your marketing, run every month",
    content: [
      statement("A marketing lead and a designer, a fixed number of days a month, with the channels you choose and a report on the first."),
      p("You do not need a marketing department; you need marketing done. This retainer gives you senior people for a fixed number of days, with paid ads and email as options you can add or drop each quarter."),
      images([{ url: ART.cool, caption: "The monthly plan" }, { url: ART.deep, caption: "Campaign assets" }]),
      h(2, "What you get", "blue"),
      grid([
        { title: "A plan each month", text: "Priorities agreed on a thirty-minute call on the first working day, written up the same day." },
        { title: "Senior hands", text: "A marketing lead and a designer, booked in advance, not a rotating cast of juniors." },
        { title: "The numbers", text: "One page on the first of the month: what went out, what it cost, what it brought in." },
      ]),
      h(2, "How it works"),
      table([
        ["Month", "Focus", "You get"],
        ["1", "Audit, positioning, the plan", "A ninety-day plan"],
        ["2 to 3", "Ship the plan, weekly check-ins", "Campaigns live, the first numbers"],
        ["Each quarter", "Review, switch channels on or off", "A revised plan"],
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("It is the first time our marketing has had a plan that survived the month.", "Chris Malone", "MD, Malone Cycles"),
      ...pricing("The retainer runs by the month. Add channels below."),
      ...terms("Billed monthly in advance with a three-month minimum, then thirty days' notice. Ad spend is paid by you directly to the platforms. Unused days do not roll over."),
    ],
    items: [
      { name: "Marketing retainer", description: "Four days a month across a lead and a designer, plan and report", unitAmount: 380000, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null, billing: "month" },
      { name: "Paid ads management", description: "Google and Meta campaigns set up and optimised weekly", unitAmount: 90000, quantity: 1, optional: true, selectedByDefault: true, taxRateBps: null, billing: "month" },
      { name: "Email newsletter", description: "Two sends a month, written and designed", unitAmount: 60000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null, billing: "month" },
      { name: "Extra days", description: "Beyond the four included", unitAmount: 95000, quantity: 0, minQuantity: 0, maxQuantity: 6, optional: true, selectedByDefault: false, taxRateBps: null, unit: "day", billing: "month" },
    ],
  },
  {
    id: "app-development",
    group: "trade",
    trade: "Web and software",
    style: "night",
    name: "App development",
    summary: "A mobile app built in phases, with a support plan and extras the client can add.",
    title: "Your app, version one",
    content: [
      statement("A first version of your app on both stores in twelve weeks, built in phases you can see, with nothing hidden until launch."),
      p("You have a clear idea and a rough sketch. This proposal turns it into a scope, a schedule and a price, with the parts that can wait for version two marked as options."),
      h(2, "What you get", "blue"),
      grid([
        { title: "Design first", text: "Clickable screens in week two, so we agree on the app before a line of code is written." },
        { title: "Built in three phases", text: "Sign-in and the core flow, then the rest, then polish. A working build on your phone after every phase." },
        { title: "On both stores", text: "Submitted to Apple and Google, with the listings written and the screenshots made." },
      ]),
      h(2, "How it works"),
      table([
        ["Weeks", "What happens", "You get"],
        ["1 to 2", "Scope and clickable design", "Screens to try on your phone"],
        ["3 to 10", "Three build phases, a build after each", "The app, growing every three weeks"],
        ["11 to 12", "Testing, store submission, launch", "Version one, live"],
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("Every three weeks there was something new on my phone. I never had to wonder what was happening.", "Sophie Laurent", "Founder, Laurent Fitness"),
      ...pricing("Choose the extras and the support plan below."),
      ...terms("Billed per phase: 25% on acceptance, 25% at design sign-off, 25% after phase two, 25% at launch. The source code is yours at each payment. Store fees are paid by you. Changes to the agreed scope are quoted before they are built."),
    ],
    items: [
      { name: "App, version one", description: "Design, three build phases, both stores", unitAmount: 3600000, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null },
      { name: "Push notifications", description: "Set up, with a simple send tool for you", unitAmount: 180000, quantity: 1, optional: true, selectedByDefault: true, taxRateBps: null },
      { name: "Payments in the app", description: "Subscriptions through the stores' billing", unitAmount: 320000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null },
      { name: "Support plan", description: "Updates for new OS versions, bug fixes, one small change a month", unitAmount: 60000, quantity: 1, optional: true, selectedByDefault: true, taxRateBps: null, billing: "month" },
    ],
  },
  {
    id: "it-support",
    group: "trade",
    trade: "Web and software",
    style: "classic",
    name: "IT support",
    summary: "Managed IT for a small office, priced per user, with backups and security as options.",
    title: "IT support for your team",
    content: [
      statement("Someone to call when a laptop dies, and the quiet work that stops it dying: updates, backups and security, for a fixed price per person."),
      p("Fifteen people, one office, no IT person. This proposal covers the help desk, the maintenance nobody sees, and the protection you need, at a price that scales with headcount."),
      h(2, "What you get", "blue"),
      grid([
        { title: "A help desk", text: "Phone and email, answered within thirty minutes in working hours, with a visit the same day if it cannot be fixed remotely." },
        { title: "Maintenance", text: "Updates, patching and monitoring on every laptop, done outside your hours." },
        { title: "New starters and leavers", text: "A laptop set up before day one; accounts closed and data kept when someone leaves." },
      ]),
      h(2, "How it works"),
      table([
        ["When", "What happens", "You get"],
        ["Month 1", "Audit of every device and account", "A list of risks, fixed in order"],
        ["Ongoing", "Help desk, patching, monitoring", "A monthly summary of tickets and uptime"],
        ["Quarterly", "A review meeting", "A plan for what to replace and when"],
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("A laptop died on a Tuesday morning. She had a new one by lunch. I did not do anything.", "Mark Ellis", "Ellis Architects"),
      ...pricing("Set the number of people below. The total updates as you go."),
      ...terms("Billed monthly in advance per user. Hardware is bought by you on our recommendation. Thirty days' notice to end. Response times are targets in working hours; out-of-hours cover is available on request."),
    ],
    items: [
      { name: "Managed IT support", description: "Per user per month: help desk, patching, monitoring", unitAmount: 6500, quantity: 15, minQuantity: 5, maxQuantity: 60, optional: false, selectedByDefault: true, taxRateBps: null, unit: "user", billing: "month" },
      { name: "Cloud backup", description: "Per user per month, daily, tested monthly", unitAmount: 1200, quantity: 15, minQuantity: 0, maxQuantity: 60, optional: true, selectedByDefault: true, taxRateBps: null, unit: "user", billing: "month" },
      { name: "Security training", description: "A one-hour session for the whole team, twice a year", unitAmount: 45000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null, billing: "quarter" },
    ],
  },
  {
    id: "translation",
    group: "trade",
    trade: "Business services",
    style: "editorial",
    name: "Translation",
    summary: "A website translated by a native speaker, priced by the word, with review and updates.",
    title: "Your website in French",
    content: [
      statement("Your site read by a native speaker and translated so it sounds written, not translated, with the tone your brand already has."),
      p("You are opening to a French-speaking market and the site needs to read like it was made there. This proposal covers the translation, a second-reader review, and keeping it current as pages change."),
      h(2, "What you get", "purple"),
      grid([
        { title: "Translated by a native", text: "Every page translated by one person, so the voice is consistent, with a glossary of your terms." },
        { title: "Reviewed by a second", text: "A second native reader checks every page before delivery." },
        { title: "Delivered ready to publish", text: "In your content system or a document, with page titles and metadata included." },
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("Our Montreal customers assumed we were a local company. That was the point.", "Rachel Kim", "Kim Ceramics"),
      ...pricing("Set the word count below. The total updates as you go."),
      ...terms("Half on acceptance, half at delivery. Word counts are taken from the source pages you send; small differences are absorbed. Two rounds of changes are included."),
    ],
    items: [
      { name: "Translation", description: "Per thousand words, translated and reviewed", unitAmount: 22000, quantity: 8, minQuantity: 1, maxQuantity: 60, optional: false, selectedByDefault: true, taxRateBps: null, unit: "thousand words" },
      { name: "Glossary and style sheet", description: "Your terms and tone, written down for every future translation", unitAmount: 30000, quantity: 1, optional: true, selectedByDefault: true, taxRateBps: null },
      { name: "Monthly updates", description: "Up to two thousand words of changed pages a month", unitAmount: 35000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null, billing: "month" },
    ],
  },
  {
    id: "tutoring",
    group: "trade",
    trade: "Events and personal",
    style: "minimal",
    name: "Tutoring",
    summary: "A term of maths tutoring with sessions the family sets, plus exam preparation.",
    title: "Maths tutoring this term",
    content: [
      statement("One hour a week, one to one, with a plan for the term and a note home after every session."),
      p("You want to know exactly what is being worked on and whether it is helping. Here is how the term runs, what each session covers, and what it costs for the number of sessions you choose."),
      h(2, "What you get", "green"),
      grid([
        { title: "A plan for the term", text: "Built from the first session and the school's topics, so we work on the right things in the right order." },
        { title: "A note after each session", text: "Three lines: what we did, what went well, what to practise before next week." },
        { title: "Exam preparation", text: "Past papers under timed conditions in the last four weeks, marked and gone through together." },
      ]),
      h(2, "What parents say", "yellow"),
      testimonial("The notes after each session meant I finally knew what was going on in maths.", "Deborah Ansah", "Parent"),
      ...pricing("Set the number of sessions for the term below."),
      ...terms("Billed monthly for the sessions in that month. Sessions cancelled with less than twenty-four hours' notice are charged. All tutors hold a current background check."),
    ],
    items: [
      { name: "One-to-one sessions", description: "One hour, in person or online", unitAmount: 5500, quantity: 12, minQuantity: 6, maxQuantity: 30, optional: false, selectedByDefault: true, taxRateBps: null, unit: "session" },
      { name: "Exam paper marking", description: "Past papers marked between sessions, per paper", unitAmount: 2500, quantity: 0, minQuantity: 0, maxQuantity: 12, optional: true, selectedByDefault: false, taxRateBps: null, unit: "paper" },
      { name: "Holiday revision course", description: "Three mornings in the break before exams", unitAmount: 24000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null },
    ],
  },
  {
    id: "architecture",
    group: "trade",
    trade: "Design",
    style: "minimal",
    name: "Architecture",
    summary: "A house extension from concept to planning, with the construction stages as options.",
    title: "Rear extension, concept to planning",
    content: [
      statement("A rear extension designed around how you live, drawn to planning standard, with the later stages priced now so there are no surprises."),
      p("You want more light and a kitchen that opens to the garden. This proposal takes the project through concept and planning, and shows what the technical and construction stages cost if you carry on with us."),
      images([{ url: ART.sage, caption: "Concept sketch" }, { url: ART.cool, caption: "Ground floor plan" }]),
      h(2, "What you get", "green"),
      grid([
        { title: "Measured survey and brief", text: "The existing house measured and drawn, and a one-page brief we both sign." },
        { title: "Two concept options", text: "Plans and a simple 3D view of each, presented at your home." },
        { title: "The planning application", text: "Drawings, forms and the design statement submitted and followed to a decision." },
      ]),
      h(2, "How it works"),
      table([
        ["Stage", "What happens", "You get"],
        ["Survey and concept", "Four weeks", "A chosen concept"],
        ["Planning", "Two weeks to prepare, eight to twelve for the decision", "Permission, or a clear next step"],
        ["Technical and construction", "Optional, priced below", "Drawings a builder can price and a project run to the end"],
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("The planners approved it first time. The builder said the drawings answered every question before he asked it.", "Ruth and Ian", "Homeowners"),
      ...pricing("The concept and planning stages are included. Add the later stages if you want us to carry on."),
      ...terms("Fees are billed at the end of each stage. Planning fees and any surveys the council asks for are paid by you directly. Either side can stop at the end of a stage."),
    ],
    items: [
      { name: "Concept and planning", description: "Survey, two concepts, the planning application", unitAmount: 620000, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null },
      { name: "Technical design", description: "Construction drawings and building regulations submission", unitAmount: 480000, quantity: 1, optional: true, selectedByDefault: true, taxRateBps: null },
      { name: "Tender and contract", description: "Three builders priced and a contract set up", unitAmount: 180000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null },
      { name: "Site visits during construction", description: "Fortnightly visits over a typical five-month build", unitAmount: 55000, quantity: 0, minQuantity: 0, maxQuantity: 12, optional: true, selectedByDefault: false, taxRateBps: null, unit: "visit" },
    ],
  },
  {
    id: "graphic-design",
    group: "trade",
    trade: "Design",
    style: "studio",
    name: "Graphic design package",
    summary: "A launch campaign designed across print and screen, with sizes the client counts up.",
    title: "Launch campaign design",
    content: [
      statement("One idea carried across posters, social, the website banner and the shop window, so the launch looks like one launch."),
      p("You are launching a new range in six weeks and every piece needs to look like it belongs together. Here is the campaign design, the pieces included, and the extras you can add by the number."),
      images([{ url: ART.warm, caption: "Key visual" }, { url: ART.deep, caption: "Applied to social" }]),
      h(2, "What you get", "orange"),
      grid([
        { title: "A key visual", text: "One strong image and headline, developed from two directions, that every piece is built from." },
        { title: "The core set", text: "A poster, a social set of six, a web banner and a shop window vinyl, all print or upload ready." },
        { title: "Files for your printer", text: "Print PDFs with bleed and the specification, and screen files sized for each platform." },
      ]),
      h(2, "How it works"),
      table([
        ["Week", "What happens", "You get"],
        ["1", "Brief and two directions", "A direction to choose"],
        ["2 to 3", "Key visual and the core set", "Everything to review in one place"],
        ["4", "Changes and final files", "A folder your printer and your team can use"],
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("Customers said the window and the Instagram looked like the same shop for the first time.", "Yusuf Demir", "Demir Home"),
      ...pricing("Add extra pieces by the number below."),
      ...terms("Half on acceptance, half on delivery of final files. Two rounds of changes on the key visual and one on each piece. Printing is arranged and paid by you; we brief the printer."),
    ],
    items: [
      { name: "Campaign design, core set", description: "Key visual, poster, six social posts, web banner, window vinyl", unitAmount: 320000, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null },
      { name: "Extra social posts", description: "Beyond the six included", unitAmount: 9000, quantity: 0, minQuantity: 0, maxQuantity: 20, optional: true, selectedByDefault: false, taxRateBps: null, unit: "post" },
      { name: "Extra print sizes", description: "Flyer, A-board or press ad from the same visual", unitAmount: 18000, quantity: 0, minQuantity: 0, maxQuantity: 8, optional: true, selectedByDefault: false, taxRateBps: null, unit: "piece" },
      { name: "Short animation", description: "The key visual animated for stories and screens, ten seconds", unitAmount: 65000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null },
    ],
  },
  {
    id: "illustration",
    group: "trade",
    trade: "Design",
    style: "warm",
    name: "Illustration",
    summary: "A set of illustrations for a website, priced by the piece, with the licence spelled out.",
    title: "Illustrations for your website",
    content: [
      statement("A family of illustrations drawn for your site, in one style, so every page looks like it came from the same hand."),
      p("You want the site to feel warmer than stock photos allow. This proposal covers a style sample, a set of illustrations by the piece, and the rights you get to use them."),
      images([{ url: ART.warm, caption: "Style sample" }, { url: ART.sage, caption: "Spot illustrations" }]),
      h(2, "What you get", "pink"),
      grid([
        { title: "A style sample first", text: "One finished illustration and a colour palette before the set is started, so the style is agreed." },
        { title: "The set", text: "Hero illustrations for the main pages and smaller spot illustrations for features, delivered as SVG and PNG." },
        { title: "Clear rights", text: "Use on your website, social accounts and printed material, worldwide, for as long as you like." },
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("People mention the drawings on our site in the first meeting. They remember us.", "Ana Costa", "Costa Financial Planning"),
      ...pricing("Set the number of hero and spot illustrations below."),
      ...terms("The style sample is billed on acceptance; the set is billed on delivery. Two rounds of changes per illustration. Rights transfer on final payment; the original files stay with the illustrator."),
    ],
    items: [
      { name: "Style sample and palette", description: "One finished illustration and the colours for the set", unitAmount: 45000, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null },
      { name: "Hero illustrations", description: "Large pieces for the main pages", unitAmount: 38000, quantity: 4, minQuantity: 1, maxQuantity: 12, optional: false, selectedByDefault: true, taxRateBps: null, unit: "illustration" },
      { name: "Spot illustrations", description: "Small pieces for features and icons", unitAmount: 12000, quantity: 8, minQuantity: 0, maxQuantity: 30, optional: true, selectedByDefault: true, taxRateBps: null, unit: "illustration" },
      { name: "Animated versions", description: "Subtle motion for the hero pieces, as Lottie files", unitAmount: 20000, quantity: 0, minQuantity: 0, maxQuantity: 12, optional: true, selectedByDefault: false, taxRateBps: null, unit: "animation" },
    ],
  },
  {
    id: "podcast-production",
    group: "trade",
    trade: "Marketing",
    style: "night",
    name: "Podcast production",
    summary: "A monthly podcast produced end to end, priced by the episode, with clips and show notes.",
    title: "Your podcast, produced every month",
    content: [
      statement("You talk, we do everything else: recording, editing, music, show notes and the clips that bring people to it."),
      p("You have the ideas and the guests and no time for the rest. This proposal covers a launch package and then a fixed price per episode for as long as you want to keep going."),
      h(2, "What you get", "purple"),
      grid([
        { title: "Launch package", text: "Artwork, intro and outro music, a trailer, and the show set up on every platform." },
        { title: "Each episode", text: "Remote recording guided by us, edited and mixed, with show notes and a transcript, published on your schedule." },
        { title: "Clips that travel", text: "Three short vertical clips per episode with captions, ready for social." },
      ]),
      h(2, "How it works"),
      table([
        ["When", "What happens", "You get"],
        ["Weeks 1 to 3", "Launch package and the first two episodes", "A show ready to announce"],
        ["Each episode", "Record, then a week to edit and publish", "An episode live, clips and notes delivered"],
        ["Monthly", "A short report", "Downloads, top episodes, where listeners come from"],
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("I record on a Tuesday and forget about it. It is live the next Tuesday and looks better than shows with a team behind them.", "Marcus Webb", "Host, The Build Hour"),
      ...pricing("Set the number of episodes a month below."),
      ...terms("The launch package is billed on acceptance. Episodes are billed monthly for the episodes produced that month. You own the recordings and the artwork. Thirty days' notice to stop."),
    ],
    items: [
      { name: "Launch package", description: "Artwork, music, trailer, platform setup", unitAmount: 180000, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null },
      { name: "Episodes", description: "Per episode, recorded, edited, published with notes and transcript", unitAmount: 45000, quantity: 4, minQuantity: 1, maxQuantity: 12, optional: false, selectedByDefault: true, taxRateBps: null, unit: "episode", billing: "month" },
      { name: "Social clips", description: "Three captioned clips per episode", unitAmount: 12000, quantity: 4, minQuantity: 0, maxQuantity: 12, optional: true, selectedByDefault: true, taxRateBps: null, unit: "episode", billing: "month" },
      { name: "Guest booking", description: "We find, invite and schedule guests to your brief", unitAmount: 40000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null, billing: "month" },
    ],
  },
  {
    id: "virtual-assistant",
    group: "trade",
    trade: "Business services",
    style: "classic",
    name: "Virtual assistant",
    summary: "A block of hours each month for inbox, diary and admin, with the hours the client sets.",
    title: "An assistant, by the hour",
    content: [
      statement("Your inbox answered, your diary kept and the admin done, for a fixed block of hours a month by one person who learns how you work."),
      p("You are spending your evenings on work that is not your work. This proposal gives you a named assistant for the hours you choose, with a short list of what they handle from day one."),
      h(2, "What you get", "blue"),
      grid([
        { title: "One named assistant", text: "The same person every month, working in your tools, with a written handover if they are ever away." },
        { title: "Inbox and diary", text: "Email triaged twice a day, meetings booked, travel arranged, reminders sent." },
        { title: "The admin", text: "Invoices raised, receipts filed, suppliers chased, documents formatted. A weekly summary on Friday." },
      ]),
      h(2, "How it works"),
      table([
        ["When", "What happens", "You get"],
        ["Week 1", "Access set up, a list of what to handle", "A running start"],
        ["Daily", "Inbox at nine and two, tasks in between", "A quieter inbox"],
        ["Friday", "A five-line summary", "What was done, what needs you"],
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("She knows which emails I care about better than I do. My evenings are mine again.", "Helen Marsh", "Marsh Consulting"),
      ...pricing("Set the hours a month below. The total updates as you go."),
      ...terms("Billed monthly in advance for the block of hours. Unused hours roll over for one month. Extra hours are billed at the same rate. Confidentiality is part of the contract and every assistant signs it."),
    ],
    items: [
      { name: "Assistant hours", description: "Per hour, in a monthly block", unitAmount: 4200, quantity: 20, minQuantity: 10, maxQuantity: 80, optional: false, selectedByDefault: true, taxRateBps: null, unit: "hour", billing: "month" },
      { name: "Bookkeeping hand-off", description: "Receipts and invoices prepared for your accountant monthly", unitAmount: 15000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null, billing: "month" },
      { name: "Out-of-hours cover", description: "Urgent messages watched evenings and weekends", unitAmount: 25000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null, billing: "month" },
    ],
  },
  {
    id: "hr-consulting",
    group: "trade",
    trade: "Business services",
    style: "editorial",
    name: "HR consulting",
    summary: "Contracts, a handbook and a hiring process for a growing team, with monthly support.",
    title: "HR foundations for a growing team",
    content: [
      statement("The contracts, the handbook and the hiring process a fifteen-person company needs, set up once and kept current."),
      p("You have hired fast and the paperwork has not kept up. This proposal puts the foundations in place in six weeks, then keeps them current with a monthly retainer if you want it."),
      h(2, "What you get", "purple"),
      grid([
        { title: "Contracts that fit", text: "An employment contract and a contractor agreement written for how you actually work, reviewed for the law where you are." },
        { title: "A handbook people read", text: "Policies in plain language: leave, remote work, expenses, conduct, and how to raise a concern." },
        { title: "A hiring process", text: "Job description template, structured interview questions, a scorecard and an offer letter." },
      ]),
      h(2, "How it works"),
      table([
        ["Week", "What happens", "You get"],
        ["1 to 2", "Audit of what exists, interviews with you and two managers", "A list of gaps in order of risk"],
        ["3 to 5", "Contracts, handbook and hiring kit written", "Documents to review"],
        ["6", "Rollout, a session with the team", "Everything signed and in place"],
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("We went from a folder of documents nobody had read to a handbook new starters actually mention.", "Leo Fischer", "COO, Fischer Robotics"),
      ...pricing("The foundations project is included. Add the monthly retainer if you want it kept current."),
      ...terms("The project is billed half on acceptance and half at rollout. Legal review by a qualified lawyer in your jurisdiction is included for the contracts; the handbook is guidance, not legal advice. The retainer runs month to month."),
    ],
    items: [
      { name: "HR foundations", description: "Audit, contracts, handbook and the hiring kit", unitAmount: 560000, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null },
      { name: "Monthly HR retainer", description: "Four hours a month: questions answered, documents updated, one manager session a quarter", unitAmount: 60000, quantity: 1, optional: true, selectedByDefault: true, taxRateBps: null, billing: "month" },
      { name: "Manager training", description: "A half-day session on hiring, feedback and difficult conversations", unitAmount: 140000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null },
    ],
  },
  {
    id: "accounting",
    group: "trade",
    trade: "Business services",
    style: "classic",
    name: "Accounting and tax",
    summary: "Year-end accounts and tax for a small company, with advisory hours the client can add.",
    title: "Year-end accounts and tax",
    content: [
      statement("Your year-end accounts prepared, your tax return filed, and a meeting where you understand both."),
      p("You want the year closed properly and you want to know what the numbers mean. This proposal covers the year-end, the corporate tax return, and the advice you can add by the hour."),
      h(2, "What you get", "green"),
      grid([
        { title: "Year-end accounts", text: "Statutory accounts prepared from your bookkeeping and filed on time, with adjustments explained." },
        { title: "The tax return", text: "The corporate return prepared and filed, reliefs claimed, the amount due and the date to pay it." },
        { title: "A review meeting", text: "An hour on the numbers: what changed, what to watch, what to do before the next year-end." },
      ]),
      h(2, "How it works"),
      table([
        ["When", "What happens", "You get"],
        ["Month after year-end", "We request the records and reconcile", "A short list of questions"],
        ["Six weeks in", "Draft accounts and the return", "Drafts to approve"],
        ["Before the deadline", "Filing and the review meeting", "Confirmation and a plan"],
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("First accountant who explained the accounts in words I understood, and filed early.", "Simone Baptiste", "Baptiste Landscapes"),
      ...pricing("Add director returns and advisory hours below."),
      ...terms("Fees are billed on filing. Records must arrive within three months of year-end to guarantee on-time filing. Advisory hours are billed monthly as used."),
    ],
    items: [
      { name: "Year-end accounts and corporate tax", description: "Prepared, filed, reviewed with you", unitAmount: 180000, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null },
      { name: "Director personal tax returns", description: "Per director", unitAmount: 28000, quantity: 1, minQuantity: 0, maxQuantity: 6, optional: true, selectedByDefault: true, taxRateBps: null, unit: "return" },
      { name: "Advisory hours", description: "Tax planning, cash flow, questions through the year", unitAmount: 18000, quantity: 0, minQuantity: 0, maxQuantity: 20, optional: true, selectedByDefault: false, taxRateBps: null, unit: "hour" },
    ],
  },
  {
    id: "web-maintenance",
    group: "trade",
    trade: "Web and software",
    style: "bold",
    name: "Website maintenance",
    summary: "A monthly care plan for an existing website, with content hours the client sets.",
    title: "Looking after your website",
    content: [
      statement("Updates, backups, security and a person to email when something needs changing, for a fixed price a month."),
      p("The site was built two years ago and nobody has touched it since. This plan keeps it fast, safe and current, with a block of hours each month for the changes you ask for."),
      h(2, "What you get", "blue"),
      grid([
        { title: "Kept up to date", text: "Platform and plugin updates tested on a copy first, then applied, every month." },
        { title: "Backed up and watched", text: "Daily backups kept for thirty days, uptime monitoring, and a security scan every week." },
        { title: "Changes done", text: "A block of hours each month for new pages, text and image changes, turned around within two working days." },
      ]),
      h(2, "How it works"),
      table([
        ["When", "What happens", "You get"],
        ["Month 1", "Audit, backups set up, overdue updates applied", "A site that is current"],
        ["Monthly", "Updates, scans, your change requests", "A two-line report"],
        ["If it breaks", "We restore from backup and fix the cause", "Back online, usually within the hour"],
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("The site went down once at 6am. It was back before I had finished my coffee, and I only found out from the report.", "Paula Brennan", "Brennan Physio"),
      ...pricing("Set the content hours a month below."),
      ...terms("Billed monthly in advance. Thirty days' notice to end. Hosting is paid by you unless you choose our hosting below. Emergencies outside working hours are covered on the plan."),
    ],
    items: [
      { name: "Care plan", description: "Updates, backups, monitoring, security scans", unitAmount: 9500, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null, billing: "month" },
      { name: "Content hours", description: "Per hour, for changes you ask for", unitAmount: 8500, quantity: 2, minQuantity: 0, maxQuantity: 20, optional: true, selectedByDefault: true, taxRateBps: null, unit: "hour", billing: "month" },
      { name: "Managed hosting", description: "Fast hosting with a CDN and a staging copy", unitAmount: 4500, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null, billing: "month" },
    ],
  },
  {
    id: "ecommerce-store",
    group: "trade",
    trade: "Web and software",
    style: "studio",
    name: "Online store build",
    summary: "A store built on a hosted platform, with product setup by the number and launch support.",
    title: "Your online store, built and launched",
    content: [
      statement("A store that looks like your brand and takes orders on day one, built on a platform you can run yourself afterwards."),
      p("You sell in person and want to sell online without hiring a developer forever. This proposal covers design, build, the products loaded, and the first month after launch."),
      images([{ url: ART.warm, caption: "Homepage" }, { url: ART.cool, caption: "Product page on a phone" }]),
      h(2, "What you get", "orange"),
      grid([
        { title: "Designed to your brand", text: "A theme customised with your colours, type and photography, not a template with your logo dropped in." },
        { title: "Set up to sell", text: "Payments, shipping rates, taxes, email receipts and the checkout tested with real orders." },
        { title: "Products loaded", text: "Your products entered with photos, variants and descriptions, by the number you choose." },
      ]),
      h(2, "How it works"),
      table([
        ["Week", "What happens", "You get"],
        ["1", "Brief, platform setup, design", "Homepage and product page designs"],
        ["2 to 3", "Build, products loaded, checkout tested", "A store on a private link"],
        ["4", "Training, launch, first month of support", "Orders, and someone to ask"],
      ]),
      h(2, "What clients say", "yellow"),
      testimonial("First online order came in the evening we launched. I ran the sale myself the next month.", "Georgia Lane", "Lane Ceramics"),
      ...pricing("Set the number of products below and add what you need."),
      ...terms("Half on acceptance, half at launch. Platform subscription and payment fees are paid by you to the platform. One month of support after launch is included; a care plan is available after that."),
    ],
    items: [
      { name: "Store design and build", description: "Theme, checkout, shipping, taxes, training, one month of support", unitAmount: 480000, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null },
      { name: "Products loaded", description: "Per product, with photos and variants", unitAmount: 1500, quantity: 40, minQuantity: 0, maxQuantity: 300, optional: true, selectedByDefault: true, taxRateBps: null, unit: "product" },
      { name: "Product photography", description: "A half-day shoot, up to forty products", unitAmount: 90000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null },
      { name: "Care plan after launch", description: "Updates, changes and support", unitAmount: 12000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null, billing: "month" },
    ],
  },
  {
    id: "real-estate-photography",
    group: "trade",
    trade: "Photography and video",
    style: "minimal",
    name: "Real estate photography",
    summary: "A listing photographed, with drone, twilight and floor plans the agent can add.",
    title: "Photography for your listing",
    content: [
      statement("Photographs that make people book a viewing, delivered the next morning, with the extras that make a listing stand out."),
      p("A good listing is decided in the first three photos. This proposal covers a full shoot of the property with everything ready to upload by nine the next morning, and the extras by the piece."),
      images([{ url: ART.sage, caption: "Living room, natural light" }, { url: ART.cool, caption: "Twilight exterior" }]),
      h(2, "What you get", "green"),
      grid([
        { title: "A full shoot", text: "Every room and the exterior, with lights and lenses that make rooms read the size they are." },
        { title: "Edited by the next morning", text: "Twenty-five to thirty-five photos, colour-corrected, sky replaced where needed, delivered before nine." },
        { title: "Ready to upload", text: "Sized for the portals and for print, in a gallery you can share with the vendor." },
      ]),
      h(2, "What agents say", "yellow"),
      testimonial("Viewings doubled on the first listing we used him for. He is on every listing now.", "Tara Quinn", "Quinn and Partners"),
      ...pricing("Add drone, twilight and floor plans below."),
      ...terms("Invoiced on delivery, due in fourteen days. Shoots cancelled with less than twenty-four hours' notice are charged at half. Photos are licensed to the agent for the marketing of this property."),
    ],
    items: [
      { name: "Property shoot", description: "Interior and exterior, up to four bedrooms, edited by next morning", unitAmount: 24000, quantity: 1, optional: false, selectedByDefault: true, taxRateBps: null },
      { name: "Drone photos", description: "Six aerial photos of the property and its setting", unitAmount: 12000, quantity: 1, optional: true, selectedByDefault: true, taxRateBps: null },
      { name: "Twilight shoot", description: "A return visit at dusk for the exterior", unitAmount: 15000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null },
      { name: "Floor plan", description: "Measured and drawn, per floor", unitAmount: 6000, quantity: 2, minQuantity: 0, maxQuantity: 5, optional: true, selectedByDefault: true, taxRateBps: null, unit: "floor" },
      { name: "Video walkthrough", description: "Ninety seconds, edited with music", unitAmount: 20000, quantity: 1, optional: true, selectedByDefault: false, taxRateBps: null },
    ],
  },
];
